import type { PrebuiltDeck } from '../types/prebuilt-deck';

export const PREBUILT_DECKS: PrebuiltDeck[] = [
  {
    id: 'deck-casual',
    name: 'Vocabulario Casual & Modismos',
    concept: 'Inglés / Español',
    category: 'Casual',
    description: 'Dominá las expresiones del día a día que no encontrás en los libros de texto.',
    icon: '🗣️',
    order: 1,
    active: true,
    associations: [
      { term: "What's up?", definition: '¿Qué tal?' },
      { term: "I'm down", definition: 'Estoy de acuerdo / Me copa' },
      { term: 'No brainer', definition: 'No hay que pensarlo' },
      { term: "That's sick!", definition: '¡Está genial!' },
      { term: 'My bad', definition: 'Fue mi culpa' },
      { term: 'Hang on', definition: 'Esperá un momento' },
      { term: "I'm broke", definition: 'Estoy sin plata' },
      { term: 'Piece of cake', definition: 'Cosita de niños / Muy fácil' },
      { term: "Let's call it a day", definition: 'Terminemos por hoy' },
      { term: 'Beat around the bush', definition: 'Ir por las ramas' },
      { term: "I'm kidding", definition: 'Estoy jodiendo / Es broma' },
      { term: 'Long time no see', definition: '¡Cuánto tiempo sin verte!' },
      { term: "What's the catch?", definition: '¿Cuá son las trampas?' },
      { term: 'Under the weather', definition: 'Estar medio enfermo' },
      { term: 'Hit the sack', definition: 'Ir a dormir' },
      { term: "I'm on it", definition: 'Ya estoy encargado' },
      { term: 'Cut to the chase', definition: 'Andá al grano' },
      { term: 'Break a leg', definition: '¡Mucha suerte!' },
      { term: "It's a deal", definition: 'Trato hecho' },
      { term: 'Chill out', definition: 'Relajate' },
    ],
  },
  {
    id: 'deck-shopping',
    name: 'En el Shopping & Tiendas',
    concept: 'Inglés / Español',
    category: 'Travel',
    description: 'Preparate para comprar, preguntar precios y devolver productos.',
    icon: '🛍️',
    order: 2,
    active: true,
    associations: [
      { term: 'How much is this?', definition: '¿Cuánto cuesta esto?' },
      { term: 'Do you have this in blue?', definition: '¿Tiene esto en azul?' },
      { term: "I'm just looking", definition: 'Solo estoy mirando' },
      { term: 'Can I try it on?', definition: '¿Puedo probarmelo?' },
      { term: 'Where is the fitting room?', definition: '¿Dónde está el probador?' },
      { term: "I'll take it", definition: 'Me lo llevo' },
      { term: 'Do you accept credit cards?', definition: '¿Aceptan tarjeta de crédito?' },
      { term: 'Can I get a receipt?', definition: '¿Me da la factura?' },
      { term: 'Is there a discount?', definition: '¿Hay descuento?' },
      { term: "It's too expensive", definition: 'Es muy caro' },
      { term: 'Can I return this?', definition: '¿Puedo devolver esto?' },
      { term: 'Do you have a bigger size?', definition: '¿Tiene talle más grande?' },
      { term: 'Where is the checkout?', definition: '¿Dónde se paga?' },
      { term: 'I need a gift receipt', definition: 'Necesito un recibo para regalo' },
      { term: "What's on sale?", definition: '¿Qué está en oferta?' },
      { term: 'Can I get a bag?', definition: '¿Me da una bolsa?' },
      { term: 'This one, please', definition: 'Este, por favor' },
      { term: 'Do you have a loyalty program?', definition: '¿Tienen programa de fidelidad?' },
      { term: 'I changed my mind', definition: 'Cambié de opinión' },
      { term: 'Thank you for your help', definition: 'Gracias por su ayuda' },
    ],
  },
  {
    id: 'deck-friends',
    name: 'Diálogos de Friends (La Serie)',
    concept: 'Inglés / Español',
    category: 'Pop Culture',
    description: 'Aprendé frases icónicas de la serie más popular para practicar conversación.',
    icon: '📺',
    order: 3,
    active: true,
    associations: [
      { term: "How you doin'?", definition: '¿Cómo estás?' },
      { term: 'We were on a break!', definition: '¡Estábamos en un break!' },
      { term: 'Pivot!', definition: '¡Girá!' },
      { term: "Oh my God!", definition: '¡Oh mi Dios!' },
      { term: "We were on a break!", definition: '¡Estábamos separados!' },
      { term: 'It\'s a moo point', definition: 'Es un punto vacuno (no importa)' },
      { term: 'He\'s her lobster', definition: 'Él es su langosta (alma gemela)' },
      { term: 'Could I BE any more...?', definition: '¿Podría ser más...?' },
      { term: 'Unagi', definition: 'Estado de alerta total' },
      { term: 'The one where...', definition: 'El capítulo en el que...' },
      { term: 'Smelly cat, smelly cat', definition: 'Gato apestoso, gato apestoso' },
      { term: 'Welcome to the real world', definition: 'Bienvenido al mundo real' },
      { term: 'I\'m not great at advice', definition: 'No soy bueno dando consejos' },
      { term: 'It\'s like all my life everyone\'s told me', definition: 'Toda la vida todos me dijeron' },
      { term: 'You\'re over me?', definition: '¿Ya superaste?' },
      { term: 'When were you under me?', definition: '¿Cuándo estuviste conmigo?' },
      { term: 'Seven! Seven! Seven!', definition: '¡Siete! ¡Siete! ¡Siete!' },
      { term: 'I know!', definition: '¡Lo sé!' },
      { term: 'We\'re on a break!', definition: '¡Estamos en un break!' },
      { term: 'Grab a spoon', definition: 'Agarrá una cuchara (entrá en la onda)' },
    ],
  },
  {
    id: 'deck-mj',
    name: 'Lírica: Michael Jackson (Thriller)',
    concept: 'Inglés / Español',
    category: 'Music',
    description: 'Memorizá la letra de Thriller y aprendé vocabulario a través de la música.',
    icon: '🎵',
    order: 4,
    active: true,
    associations: [
      { term: "It's close to midnight", definition: 'Está cerca de la medianoche' },
      { term: "Something evil's lurking from the dark", definition: 'Algo malvado acecha desde la oscuridad' },
      { term: "Under the moonlight", definition: 'Bajo la luz de la luna' },
      { term: "You try to scream", definition: 'Intentás gritar' },
      { term: "But terror takes the sound before you make it", definition: 'Pero el terror te quita el sonido antes de que puedas' },
      { term: "You start to freeze", definition: 'Empezás a congelarte' },
      { term: "As horror looks you right between the eyes", definition: 'Mientras el terror te mira justo a los ojos' },
      { term: "They're out to get you", definition: 'Salen a por ti' },
      { term: "Closing off your mind", definition: 'Cerrando tu mente' },
      { term: "But no one saves you from the beast about to strike", definition: 'Pero nadie te salva de la bestia a punto de atacar' },
      { term: "You know it's thriller night", definition: 'Sabés que es noche de thriller' },
      { term: "And no one's gonna save you", definition: 'Y nadie va a salvarte' },
      { term: "From the beast about to strike", definition: 'De la bestia a punto de atacar' },
      { term: "You're fighting for your life", definition: 'Estás peleando por tu vida' },
      { term: "Inside a killer, thriller tonight", definition: 'Dentro de un asesino, thriller esta noche' },
    ],
  },
];
