export const STOPWORDS_EN = new Set([
  'a', 'an', 'and', 'are', 'as', 'at', 'be', 'by', 'for', 'from', 'in', 'into',
  'is', 'it', 'of', 'on', 'or', 'that', 'the', 'this', 'to', 'was', 'with',
  'i', 'you', 'he', 'she', 'we', 'they', 'me', 'him', 'her', 'us', 'them',
  'my', 'your', 'his', 'her', 'its', 'our', 'their', 'mine', 'yours', 'hers',
  'ours', 'theirs', 'myself', 'yourself', 'himself', 'herself', 'itself',
  'ourselves', 'yourselves', 'themselves', 'am', 'is', 'are', 'was', 'were',
  'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did',
  'doing', 'will', 'would', 'shall', 'should', 'can', 'could', 'may', 'might',
  'must', 'ought', 'need', 'dare', 'used', 'use', 'using', 'make', 'made',
  'makes', 'making', 'go', 'goes', 'went', 'gone', 'going', 'see', 'sees',
  'saw', 'seen', 'seeing', 'get', 'gets', 'got', 'gotten', 'getting', 'come',
  'comes', 'came', 'coming', 'know', 'knows', 'knew', 'known', 'knowing',
  'think', 'thinks', 'thought', 'thinking', 'say', 'says', 'said', 'saying',
  'tell', 'tells', 'told', 'telling', 'ask', 'asks', 'asked', 'asking',
  'give', 'gives', 'gave', 'given', 'giving', 'take', 'takes', 'took', 'taken',
  'taking', 'work', 'works', 'worked', 'working', 'seem', 'seems', 'seemed',
  'seeming', 'feel', 'feels', 'felt', 'feeling', 'try', 'tries', 'tried',
  'trying', 'leave', 'leaves', 'left', 'leaving', 'call', 'calls', 'called',
  'calling', 'want', 'wants', 'wanted', 'wanting', 'need', 'needs', 'needed',
  'needing', 'use', 'uses', 'used', 'using', 'find', 'finds', 'found',
  'finding', 'give', 'gives', 'gave', 'given', 'giving', 'tell', 'tells',
  'told', 'telling', 'ask', 'asks', 'asked', 'asking', 'seem', 'seems',
  'seemed', 'seeming', 'feel', 'feels', 'felt', 'feeling', 'become', 'becomes',
  'became', 'become', 'becoming', 'begin', 'begins', 'began', 'begun',
  'beginning', 'seem', 'seems', 'seemed', 'seeming', 'help', 'helps', 'helped',
  'helping', 'show', 'shows', 'showed', 'shown', 'showing', 'hear', 'hears',
  'heard', 'hearing', 'play', 'plays', 'played', 'playing', 'run', 'runs',
  'ran', 'run', 'running', 'move', 'moves', 'moved', 'moving', 'live', 'lives',
  'lived', 'living', 'believe', 'believes', 'believed', 'believing', 'bring',
  'brings', 'brought', 'bringing', 'happen', 'happens', 'happened', 'happening',
  'write', 'writes', 'wrote', 'written', 'writing', 'sit', 'sits', 'sat',
  'sitting', 'stand', 'stands', 'stood', 'standing', 'lose', 'loses', 'lost',
  'losing', 'pay', 'pays', 'paid', 'paying', 'meet', 'meets', 'met', 'meeting',
  'include', 'includes', 'included', 'including', 'continue', 'continues',
  'continued', 'continuing', 'set', 'sets', 'set', 'setting', 'learn', 'learns',
  'learned', 'change', 'changes', 'changed', 'changing', 'lead',
  'leads', 'led', 'leading', 'understand', 'understands', 'understood',
  'understanding', 'watch', 'watches', 'watched', 'watching', 'follow', 'follows',
  'followed', 'following', 'stop', 'stops', 'stopped', 'stopping', 'create',
  'creates', 'created', 'creating', 'speak', 'speaks', 'spoke', 'spoken',
  'speaking', 'read', 'reads', 'read', 'reading', 'allow', 'allows', 'allowed',
  'allowing', 'add', 'adds', 'added', 'adding', 'spend', 'spends', 'spent',
  'spending', 'grow', 'grows', 'grew', 'grown', 'growing', 'open', 'opens',
  'opened', 'opening', 'walk', 'walks', 'walked', 'walking', 'win', 'wins',
  'won', 'winning', 'offer', 'offers', 'offered', 'offering', 'remember',
  'remembers', 'remembered', 'remembering', 'love', 'loves', 'loved', 'loving',
  'consider', 'considers', 'considered', 'considering', 'appear', 'appears',
  'appeared', 'appearing', 'buy', 'buys', 'bought', 'buying', 'wait', 'waits',
  'waited', 'waiting', 'serve', 'serves', 'served', 'serving', 'die', 'dies',
  'died', 'dying', 'send', 'sends', 'sent', 'sending', 'expect', 'expects',
  'expected', 'expecting', 'build', 'builds', 'built', 'building', 'stay',
  'stays', 'stayed', 'staying', 'fall', 'falls', 'fell', 'fallen', 'falling',
  'cut', 'cuts', 'cut', 'cutting', 'reach', 'reaches', 'reached', 'reaching',
  'kill', 'kills', 'killed', 'killing', 'remain', 'remains', 'remained',
  'remaining', 'suggest', 'suggests', 'suggested', 'suggesting', 'raise',
  'raises', 'raised', 'raising', 'pass', 'passes', 'passed', 'passing', 'sell',
  'sells', 'sold', 'selling', 'require', 'requires', 'required', 'requiring',
  'report', 'reports', 'reported', 'reporting', 'decide', 'decides', 'decided',
  'deciding', 'pull', 'pulls', 'pulled', 'pulling', 'return', 'returns',
  'returned', 'returning', 'explain', 'explains', 'explained', 'explaining',
  'hope', 'hopes', 'hoped', 'hoping', 'develop', 'develops', 'developed',
  'developing', 'carry', 'carries', 'carried', 'carrying', 'break', 'breaks',
  'broke', 'broken', 'breaking', 'receive', 'receives', 'received', 'receiving',
  'agree', 'agrees', 'agreed', 'agreeing', 'support', 'supports', 'supported',
  'supporting', 'hit', 'hits', 'hit', 'hitting', 'produce', 'produces', 'produced',
  'producing', 'eat', 'eats', 'ate', 'eaten', 'eating', 'teach', 'teaches',
  'taught', 'teaching', 'catch', 'catches', 'caught', 'catching', 'choose',
  'chooses', 'chose', 'chosen', 'choosing', 'cause', 'causes', 'caused',
  'causing', 'point', 'points', 'pointed', 'pointing', 'mean', 'means', 'meant',
  'meaning',
]);