export const STOPWORDS_ES = new Set([
  'a', 'al', 'ante', 'bajo', 'cabe', 'con', 'contra', 'de', 'desde', 'durante',
  'en', 'entre', 'hacia', 'hasta', 'mediante', 'para', 'por', 'según', 'sin',
  'so', 'sobre', 'tras', 'versus', 'vía', 'un', 'una', 'unos', 'unas', 'el',
  'la', 'los', 'las', 'lo', 'y', 'e', 'ni', 'que', 'o', 'u', 'pero', 'sino',
  'si', 'no', 'se', 'su', 'sus', 'es', 'son', 'está', 'están', 'era', 'eran',
  'fue', 'fueron', 'ser', 'estar', 'haber', 'tener', 'hacer', 'ir', 'ver',
  'dar', 'saber', 'querer', 'llegar', 'pasar', 'deber', 'poner', 'parecer',
  'quedar', 'creer', 'hablar', 'llevar', 'dejar', 'seguir', 'encontrar',
  'llamar', 'venir', 'pensar', 'salir', 'volver', 'tomar', 'conocer', 'vivir',
  'sentir', 'tratar', 'mirar', 'contar', 'empezar', 'esperar', 'buscar',
  'existir', 'entrar', 'trabajar', 'escribir', 'perder', 'producir', 'ocurrir',
  'entender', 'pedir', 'recibir', 'recordar', 'terminar', 'permitir', 'aparecer',
  'conseguir', 'leer', 'crear', 'morir', 'seguir', 'cambiar', 'presentar',
  'resultar', 'escuchar', 'cortar', 'causar', 'ayudar', 'usar', 'ganar',
  'empezar', 'probar', 'olvidar', 'pagar', 'servir', 'lograr', 'necesitar',
  'comenzar', 'decidir', 'intentar', 'preferir', 'aprender', 'enseñar', 'oír',
  'comer', 'come', 'comes', 'comemos', 'comen', 'beber', 'bebo', 'bebes', 'bebemos', 'beben',
  'dormir', 'duermo', 'duermes', 'duerme', 'dormimos', 'duermen', 'despertar', 'me despierto',
  'levantar', 'me levanto', 'sentar', 'me siento', 'acostar', 'me acuesto',
  'abrir', 'abro', 'abres', 'abre', 'abrimos', 'abren', 'cerrar', 'cierro',
  'encender', 'enciendo', 'apagar', 'apago', 'subir', 'subo', 'bajar', 'bajo',
  'entrar', 'entro', 'salir', 'salgo', 'ir', 'voy', 'vas', 'va', 'vamos', 'van',
  'venir', 'vengo', 'viene', 'andamos', 'andáis', 'andar', 'correr', 'corro',
  'saltar', 'salto', 'nadar', 'nado', 'volar', 'vuelo', 'conducir', 'conduzco',
  'viajar', 'viajo', 'llegar', 'llego', 'partir', 'parto', 'quedar', 'me quedo',
  'volver', 'vuelvo', 'regresar', 'regreso', 'continuar', 'continúo',
  'parar', 'paro', 'detener', 'detengo', 'empezar', 'empiezo', 'acabar', 'acabo',
  'terminar', 'termino', 'finalizar', 'finalizo', 'comenzar', 'comienzo',
  'iniciar', 'inicio', 'emprender', 'emprendo', 'proseguir', 'prosigo', 'seguir', 'sigo',
  'mantener', 'mantengo', 'sostener', 'sostengo', 'conservar', 'conservo',
  'guardar', 'guardo', 'proteger', 'protejo', 'defender', 'defiendo', 'cuidar', 'cuido',
  'vigilar', 'vigilo', 'observar', 'observo', 'mirar', 'miro', 'ver', 'veo',
  'notar', 'noto', 'percibir', 'percibo', 'sentir', 'siento', 'experimentar', 'experimento',
  'vivir', 'vivo', 'sufrir', 'sufro', 'disfrutar', 'disfruto', 'gozar', 'gozo',
  'padecer', 'padezco', 'soportar', 'soporto', 'aguantar', 'aguanto', 'tolerar', 'tolero',
  'resistir', 'resisto', 'aceptar', 'acepto', 'rechazar', 'rechazo', 'negar', 'niego',
  'afirmar', 'afirmo', 'confirmar', 'confirmo', 'negar', 'niego',
  'mentir', 'miento', 'decir', 'digo', 'dices', 'dice', 'decimos', 'dicen', 'contar', 'cuento',
  'relatar', 'relato', 'narrar', 'narro', 'describir', 'describo', 'explicar', 'explico',
  'exponer', 'expongo', 'presentar', 'presento', 'mostrar', 'muestro', 'demostrar', 'demuestro',
  'probar', 'pruebo', 'comprobar', 'compruebo', 'verificar', 'verifico', 'confirmar', 'confirmo',
  'validar', 'valido', 'autorizar', 'autorizo', 'aprobar', 'apruebo', 'rechazar', 'rechazo',
  'denegar', 'nego', 'negar', 'niego', 'permitir', 'permito', 'prohibir', 'prohíbo',
  'obligar', 'obligo', 'forzar', 'fuerzo', 'coaccionar', 'coacciono', 'presionar', 'presiono',
  'instigar', 'instigo', 'incitar', 'incito', 'animar', 'animo', 'alentar', 'aliento',
  'estimular', 'estimulo', 'motivar', 'motivo', 'inspirar', 'inspiro', 'inflamar', 'inflamo',
  'excitar', 'excito', 'provocar', 'provoco', 'causar', 'causo', 'originar', 'origino',
  'generar', 'genero', 'producir', 'produzco', 'crear', 'creo', 'formar', 'formo',
  'construir', 'construyo', 'edificar', 'edifico', 'levantar', 'levanto', 'fabricar', 'fabrico',
  'elaborar', 'elaboro', 'producir', 'produzco', 'manufacturar', 'manufacturo',
  'industrializar', 'industrializo', 'mecanizar', 'mecanizo', 'automatizar', 'automatizo',
  'informaticizar', 'informaticizo', 'digitalizar', 'digitalizo', 'virtualizar', 'virtualizo',
  'simular', 'simulo', 'modelar', 'modelo', 'representar', 'represento', 'simbolizar', 'simbolizo',
  'significar', 'significo', 'denotar', 'denoto', 'connotar', 'connoto', 'implicar', 'implico',
  'entrañar', 'entraño', 'conllevar', 'conllevo', 'acarrear', 'acarreo', 'arrastrar', 'arrastro',
  'traer', 'traigo', 'llevar', 'llevo', 'transportar', 'transporto', 'trasladar', 'traslado',
  'mover', 'muevo', 'desplazar', 'desplazo', 'remover', 'remuevo', 'cambiar', 'cambio',
  'alterar', 'altero', 'modificar', 'modifico', 'transformar', 'transformo', 'convertir', 'convierto',
  'transmutar', 'transmuto', 'metamorfosear', 'metamorfoseo', 'evolucionar', 'evoluciono',
  'desarrollar', 'desarrollo', 'crecer', 'crezco', 'madurar', 'maduro', 'envejecer', 'envejezco',
  'morir', 'muero', 'nacer', 'nazco', 'vivir', 'vivo', 'existir', 'existo', 'ser', 'soy', 'eres', 'es', 'somos', 'son',
  'estar', 'estoy', 'estás', 'está', 'estamos', 'están',
]);