export const STT_TEST_WORDS = [
  { word: 'hello', group: 'basic' },
  { word: 'yes', group: 'basic' },
  { word: 'no', group: 'basic' },
  { word: 'thanks', group: 'basic' },
  { word: 'please', group: 'basic' },
  { word: 'water', group: 'basic' },
  { word: 'house', group: 'basic' },
  { word: 'tree', group: 'basic' },
  { word: 'book', group: 'basic' },
  { word: 'phone', group: 'basic' },
  { word: 'sea', group: 'homophones' },
  { word: 'see', group: 'homophones' },
  { word: 'right', group: 'homophones' },
  { word: 'write', group: 'homophones' },
  { word: 'hear', group: 'homophones' },
  { word: 'here', group: 'homophones' },
  { word: 'night', group: 'homophones' },
  { word: 'knight', group: 'homophones' },
  { word: 'flour', group: 'homophones' },
  { word: 'flower', group: 'homophones' },
  { word: 'pair', group: 'homophones' },
  { word: 'pear', group: 'homophones' },
  { word: 'meat', group: 'homophones' },
  { word: 'meet', group: 'homophones' },
  { word: 'sun', group: 'homophones' },
  { word: 'son', group: 'homophones' },
  { word: 'wait', group: 'homophones' },
  { word: 'weight', group: 'homophones' },
] as const;

export type SttTestWord = typeof STT_TEST_WORDS[number];
